<?php
/**
 * Este arquivo é parte do programa Quack BB
 *
 * Quack BB é um software livre; você pode redistribuí-lo e/ou
 * modificá-lo dentro dos termos da Licença Pública Geral GNU como
 * publicada pela Fundação do Software Livre (FSF); na versão 3 da
 * Licença, ou (na sua opinião) qualquer versão.
 *
 * Este programa é distribuído na esperança de que possa ser  útil,
 * mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO
 * a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU para maiores detalhes.
 *
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU junto
 * com este programa, Se não, veja <http://www.gnu.org/licenses/>.
 *
 * @category   Quack
 * @package    Quack_BB
 * @author     Rafael Patro <rafaelpatro@gmail.com>
 * @copyright  Copyright (c) 2015 Rafael Patro (rafaelpatro@gmail.com)
 * @license    http://www.gnu.org/licenses/gpl.txt
 * @link       https://github.com/rafaelpatro/Quack_BB
 */

/**
 * @var $this Mage_Payment_Block_Info
 */
?>
<?php $method = $this->getOrder() ? $this->getOrder()->getPayment()->getMethod() : ''; ?>
<?php if ($method == 'bb_standard'): ?>
	<br />
	<a style="font-weight: bold" href="<?php echo Mage::getUrl("bb/standard/redirect/order_id/{$this->getOrder()->getId()}") ?>"><?php echo Mage::helper('bb')->__('Pagar Online no Banco do Brasil') ?></a>
	<?php if ($this->getOrder()->getPayment()->getMethodInstance()->getConfigData('allowbanktransfer') == 1): ?>
	<br />ou<br />
	<a style="font-weight: bold" href="<?php echo Mage::helper('cms/page')->getPageUrl( $this->getOrder()->getPayment()->getMethodInstance()->getConfigData('cms_banktransfer_page') ) ?>"><?php echo Mage::helper('bb')->__('Pagar no Caixa (ver dados banc&aacute;rios)') ?></a>
	<?php endif; ?>
	<br />
	<i><?php echo Mage::helper('bb')->__('Se já realizou o pagamento, aguarde a compensação. Você receberá uma confirmação em breve.') ?></i>
<?php endif; ?>